version: "3"

services:
  sonarqube:
    image: sonarqube:10.3-community
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - buscalo-net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://buscalo-db:3306/buscalo_db
      - SONARQUBE_JDBC_USERNAME=crizcode
      - SONARQUBE_JDBC_PASSWORD=48594859
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Usa hasta el 50% de un núcleo
          memory: 1G   # Usa hasta 1 GB de memoria
        reservations:
          cpus: '0.1'  # Reserva al menos el 10% de un núcleo
          memory: 512M # Reserva al menos 512 MB de memoria

  buscalo-db:
    image: mysql:latest
    networks:
      - buscalo-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=buscalo_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=usr
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  buscalo-net:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  mysql_data:
